export default function TermsOfService() {
  return (
    <main className="min-h-screen bg-[#0f172a] text-white px-6 py-12 max-w-3xl mx-auto">
      <h1 className="text-3xl font-bold mb-6">Terms of Service</h1>
      <p className="text-sm text-slate-400 mb-8">Last updated: February 9, 2026</p>

      <section className="space-y-6 text-slate-300 text-sm leading-relaxed">
        <div>
          <h2 className="text-lg font-semibold text-white mb-2">1. Acceptance of Terms</h2>
          <p>By accessing or using CarCode AI, you agree to be bound by these Terms of Service. If you do not agree, please do not use the app.</p>
        </div>

        <div>
          <h2 className="text-lg font-semibold text-white mb-2">2. Description of Service</h2>
          <p>CarCode AI is a vehicle diagnostic tool that uses artificial intelligence to analyze OBD-II trouble codes and symptom descriptions. The app provides potential causes, severity assessments, and suggested fixes for vehicle issues.</p>
        </div>

        <div>
          <h2 className="text-lg font-semibold text-white mb-2">3. Disclaimer</h2>
          <p><strong>CarCode AI is for informational purposes only.</strong> The diagnostic information provided is generated by AI and should not be considered a substitute for professional mechanical advice, inspection, or repair.</p>
          <p className="mt-2">We do not guarantee the accuracy, completeness, or reliability of any diagnostic results. Always consult a qualified mechanic before making repair decisions based on information from this app.</p>
        </div>

        <div>
          <h2 className="text-lg font-semibold text-white mb-2">4. User Accounts</h2>
          <p>You are responsible for maintaining the confidentiality of your account credentials. You agree to provide accurate information when creating an account and to notify us of any unauthorized use.</p>
        </div>

        <div>
          <h2 className="text-lg font-semibold text-white mb-2">5. Acceptable Use</h2>
          <p>You agree not to:</p>
          <ul className="list-disc list-inside mt-2 space-y-1">
            <li>Use the service for any unlawful purpose</li>
            <li>Attempt to gain unauthorized access to the service or its systems</li>
            <li>Interfere with or disrupt the service</li>
            <li>Use automated means to access the service without permission</li>
          </ul>
        </div>

        <div>
          <h2 className="text-lg font-semibold text-white mb-2">6. Intellectual Property</h2>
          <p>All content, features, and functionality of CarCode AI are owned by us and are protected by copyright and other intellectual property laws.</p>
        </div>

        <div>
          <h2 className="text-lg font-semibold text-white mb-2">7. Limitation of Liability</h2>
          <p>To the fullest extent permitted by law, CarCode AI and its creators shall not be liable for any indirect, incidental, special, consequential, or punitive damages resulting from your use of or inability to use the service, including any vehicle repairs or decisions made based on diagnostic results.</p>
        </div>

        <div>
          <h2 className="text-lg font-semibold text-white mb-2">8. Changes to Terms</h2>
          <p>We reserve the right to modify these terms at any time. Continued use of the app after changes constitutes acceptance of the new terms.</p>
        </div>

        <div>
          <h2 className="text-lg font-semibold text-white mb-2">9. Contact</h2>
          <p>If you have questions about these Terms of Service, please contact us through the app.</p>
        </div>
      </section>

      <div className="mt-10">
        <a href="/" className="text-blue-400 hover:text-blue-300 text-sm transition">← Back to CarCode AI</a>
      </div>
    </main>
  );
}
